"""
TruthSetu — Complete Setup & Seed Script
=========================================
Run this ONCE before starting development.

What this script does:
  1. Installs all required packages
  2. Creates MongoDB Atlas collections + indexes
  3. Scrapes Alt News + BOOM Live for real debunked claims
  4. Seeds 100+ known Indian fake claims from hardcoded archive
  5. Builds FAISS index from trusted RSS sources
  6. Saves everything ready for TruthSetu to use

Usage:
  python setup_and_seed.py

Requirements:
  - Python 3.11+
  - MongoDB Atlas URI (you'll be prompted)
  - Internet connection
"""

import os
import sys
import json
import time
import asyncio
import subprocess
from datetime import datetime
from pathlib import Path

# ─────────────────────────────────────────────────────────────
# STEP 0 — Install dependencies
# ─────────────────────────────────────────────────────────────

PACKAGES = [
    "pymongo",
    "motor",
    "sentence-transformers",
    "faiss-cpu",
    "numpy",
    "feedparser",
    "requests",
    "beautifulsoup4",
    "python-dotenv",
    "loguru",
    "tqdm",
    "httpx",
]

def install_packages():
    print("\n[1/6] Installing packages...")
    for pkg in PACKAGES:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", pkg, "-q"]
        )
    print("      ✓ All packages installed")

install_packages()

# Now import after install
import numpy as np
import feedparser
import requests
from bs4 import BeautifulSoup
from loguru import logger
from tqdm import tqdm
from pymongo import MongoClient, ASCENDING, TEXT
from sentence_transformers import SentenceTransformer
import faiss

# ─────────────────────────────────────────────────────────────
# STEP 1 — Configuration
# ─────────────────────────────────────────────────────────────

print("\n[2/6] Configuration")
print("─" * 50)

# MongoDB URI
MONGODB_URI = input(
    "\nPaste your MongoDB Atlas URI\n"
    "(format: mongodb+srv://user:pass@cluster.mongodb.net)\n"
    "> "
).strip()

if not MONGODB_URI:
    MONGODB_URI = "mongodb://localhost:27017"
    print("  → Using local MongoDB (localhost:27017)")

DB_NAME        = "truthsetu"
FAISS_DIR      = Path("./data/faiss_index")
ENV_FILE       = Path(".env")
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

# Create directories
FAISS_DIR.mkdir(parents=True, exist_ok=True)
Path("./data").mkdir(exist_ok=True)

# Write .env file
env_content = f"""# TruthSetu Environment Variables
# Generated by setup_and_seed.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}

# ── App ───────────────────────────────
APP_NAME=TruthSetu
APP_ENV=development
APP_PORT=8000

# ── LLM (Groq — free tier) ───────────
LLM_PROVIDER=groq
GROQ_API_KEY=your_groq_api_key_here
GROQ_MODEL=llama-3.1-8b-instant

# ── LLM (Ollama — local fallback) ────
# LLM_PROVIDER=ollama
# OLLAMA_BASE_URL=http://localhost:11434
# OLLAMA_MODEL=mistral

# ── Database ─────────────────────────
MONGODB_URI={MONGODB_URI}
MONGODB_DB_NAME={DB_NAME}

# ── Redis (Upstash free tier) ─────────
REDIS_URL=redis://localhost:6379/0

# ── Embeddings & FAISS ───────────────
EMBEDDING_MODEL={EMBEDDING_MODEL}
FAISS_INDEX_PATH=./data/faiss_index

# ── WhatsApp (Green API) ─────────────
GREEN_API_INSTANCE_ID=your_instance_id
GREEN_API_TOKEN=your_token

# ── Telegram ─────────────────────────
TELEGRAM_BOT_TOKEN=your_bot_token
TELEGRAM_DEPLOY_CHANNEL=@your_channel

# ── Twitter/X ────────────────────────
TWITTER_BEARER_TOKEN=your_bearer_token

# ── Trusted RSS Sources ───────────────
PIB_RSS=https://pib.gov.in/RssMain.aspx?ModID=6&Lang=1
IMD_RSS=https://mausam.imd.gov.in/imd_latest/contents/rss-feed.php
WHO_RSS=https://www.who.int/rss-feeds/news-releases.xml
NDMA_RSS=https://ndma.gov.in/RSS/ndma.xml
HINDU_RSS=https://www.thehindu.com/news/feeder/default.rss
IE_RSS=https://indianexpress.com/feed/
NDTV_RSS=https://feeds.feedburner.com/ndtvnews-top-stories
ALTNEWS_RSS=https://www.altnews.in/feed/
BOOM_RSS=https://www.boomlive.in/feed
"""

ENV_FILE.write_text(env_content, encoding="utf-8")
print(f"  ✓ .env file created")

# ─────────────────────────────────────────────────────────────
# STEP 2 — MongoDB setup
# ─────────────────────────────────────────────────────────────

print("\n[3/6] Setting up MongoDB...")
print("─" * 50)

client = MongoClient(MONGODB_URI, serverSelectionTimeoutMS=10000)
try:
    client.admin.command("ping")
    print("  ✓ MongoDB connected")
except Exception as e:
    print(f"  ✗ MongoDB connection failed: {e}")
    print("  → Check your URI and try again")
    sys.exit(1)

db = client[DB_NAME]

# Create collections with indexes
collections_config = [
    {
        "name": "claims",
        "indexes": [
            [("detected_at", ASCENDING)],
            [("platform", ASCENDING)],
            [("status", ASCENDING)],
            [("sender_number", ASCENDING)],
            [("claim_text", TEXT)],
        ]
    },
    {
        "name": "verdicts",
        "indexes": [
            [("verified_at", ASCENDING)],
            [("verdict", ASCENDING)],
            [("credibility_score", ASCENDING)],
            [("claim_type", ASCENDING)],
        ]
    },
    {
        "name": "templates",
        "indexes": [
            [("crisis_type", ASCENDING)],
            [("occurrence_count", ASCENDING)],
            [("verdict", ASCENDING)],
            [("template_text", TEXT)],
        ]
    },
    {
        "name": "translations",
        "indexes": [
            [("verdict_id", ASCENDING)],
            [("translated_at", ASCENDING)],
        ]
    },
    {
        "name": "deployments",
        "indexes": [
            [("verdict_id", ASCENDING)],
            [("deployed_at", ASCENDING)],
            [("status", ASCENDING)],
        ]
    },
    {
        "name": "source_scores",
        "indexes": [
            [("source", ASCENDING)],
        ]
    },
    {
        "name": "training_data",
        "indexes": [
            [("label", ASCENDING)],
            [("date", ASCENDING)],
            [("source", ASCENDING)],
        ]
    },
    {
        "name": "conversations",
        "indexes": [
            [("sender_number", ASCENDING)],
            [("received_at", ASCENDING)],
            [("status", ASCENDING)],
        ]
    },
]

for col_config in collections_config:
    col_name = col_config["name"]
    col = db[col_name]
    for index in col_config["indexes"]:
        try:
            col.create_index(index)
        except Exception:
            pass
    print(f"  ✓ Collection '{col_name}' ready")

# ─────────────────────────────────────────────────────────────
# STEP 3 — Known Indian fake claims (hardcoded archive)
# ─────────────────────────────────────────────────────────────

print("\n[4/6] Loading known fake claims archive...")
print("─" * 50)

KNOWN_FAKE_CLAIMS = [

    # ── CYCLONE / WEATHER ──────────────────────────────────
    {
        "claim": "Cyclone will hit Chennai in 2 hours, evacuate immediately to railway station",
        "template": "[DISASTER] will hit [CITY] in [TIME], evacuate to [LOCATION]",
        "crisis_type": "cyclone",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 6,
        "source": "altnews.in",
        "explanation": "IMD forecasts never specify 2-hour landfall windows on WhatsApp forwards"
    },
    {
        "claim": "Cyclone Michaung will submerge entire Chennai by tonight",
        "template": "[DISASTER] will submerge entire [CITY] by [TIME]",
        "crisis_type": "cyclone",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 5,
        "source": "boomlive.in",
        "explanation": "Cyclone submerging entire cities is meteorologically impossible"
    },
    {
        "claim": "Government has ordered mandatory evacuation of all Chennai residents",
        "template": "Government ordered mandatory evacuation of all [CITY] residents",
        "crisis_type": "cyclone",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 8,
        "source": "altnews.in",
        "explanation": "Mass city-wide evacuations are never ordered via WhatsApp forwards"
    },
    {
        "claim": "Cyclone will bring 3 meter waves destroying Marina Beach completely",
        "template": "[DISASTER] will bring [HEIGHT] waves destroying [LOCATION] completely",
        "crisis_type": "cyclone",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 7,
        "source": "boomlive.in",
        "explanation": "Wave height predictions of this magnitude don't come via forwards"
    },
    {
        "claim": "IMD has issued red alert for 15 districts in Tamil Nadu due to cyclone",
        "template": "IMD issued red alert for [NUMBER] districts in [STATE]",
        "crisis_type": "cyclone",
        "claim_type": "EPHEMERAL",
        "verdict": "UNVERIFIABLE",
        "score": 45,
        "source": "ndtv.com",
        "explanation": "Verify directly at mausam.imd.gov.in"
    },

    # ── FLOODS ─────────────────────────────────────────────
    {
        "claim": "Mullaperiyar dam has broken, Kerala will flood in 30 minutes",
        "template": "[DAM] dam has broken, [STATE/CITY] will flood in [TIME]",
        "crisis_type": "flood",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 4,
        "source": "altnews.in",
        "explanation": "This exact fake claim recurs every Kerala monsoon season since 2018"
    },
    {
        "claim": "Banasura Sagar dam has developed cracks, immediate evacuation needed",
        "template": "[DAM] has developed cracks, immediate evacuation needed",
        "crisis_type": "flood",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 6,
        "source": "boomlive.in",
        "explanation": "Dam crack rumors are perennial flood misinformation in Kerala"
    },
    {
        "claim": "Drinking water supply in Mumbai is contaminated due to floods",
        "template": "Drinking water in [CITY] is contaminated due to [DISASTER]",
        "crisis_type": "flood",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 12,
        "source": "altnews.in",
        "explanation": "BMC issues official water advisories, not WhatsApp forwards"
    },
    {
        "claim": "Yamuna will cross 210 meters tonight, Delhi will submerge",
        "template": "[RIVER] will cross [LEVEL] tonight, [CITY] will submerge",
        "crisis_type": "flood",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 10,
        "source": "boomlive.in",
        "explanation": "Yamuna flood level updates come from CWC, not social media"
    },
    {
        "claim": "Assam floods have killed 5000 people, government hiding death toll",
        "template": "[EVENT] killed [NUMBER] people, government hiding death toll",
        "crisis_type": "flood",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 8,
        "source": "altnews.in",
        "explanation": "Death toll manipulation claims recur in every major Indian flood"
    },

    # ── HEALTH / PANDEMIC ──────────────────────────────────
    {
        "claim": "COVID vaccine contains microchips to track Indian citizens",
        "template": "[VACCINE] contains [FOREIGN_OBJECT] to track citizens",
        "crisis_type": "pandemic",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 2,
        "source": "boomlive.in",
        "explanation": "Debunked globally. Microchips cannot be injected via syringe"
    },
    {
        "claim": "Drinking cow urine cures COVID completely within 3 days",
        "template": "Drinking [SUBSTANCE] cures [DISEASE] within [TIME]",
        "crisis_type": "pandemic",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 1,
        "source": "altnews.in",
        "explanation": "No scientific evidence. WHO and ICMR both refuted this claim"
    },
    {
        "claim": "5G towers are spreading COVID-19 across India",
        "template": "5G towers are spreading [DISEASE] across [LOCATION]",
        "crisis_type": "pandemic",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 1,
        "source": "boomlive.in",
        "explanation": "Viruses cannot travel on radio waves. Debunked by WHO"
    },
    {
        "claim": "New virus spreading in China will reach India in 2 weeks",
        "template": "New virus spreading in [COUNTRY] will reach India in [TIME]",
        "crisis_type": "pandemic",
        "claim_type": "EPHEMERAL",
        "verdict": "UNVERIFIABLE",
        "score": 35,
        "source": "thehindu.com",
        "explanation": "Check WHO and MoHFW for official disease surveillance updates"
    },
    {
        "claim": "Government will impose lockdown tomorrow across all states",
        "template": "Government will impose lockdown [TIME] across [LOCATION]",
        "crisis_type": "pandemic",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 8,
        "source": "altnews.in",
        "explanation": "Lockdown announcements come via official press conferences, not forwards"
    },
    {
        "claim": "Dengue mosquitoes released by government to control population",
        "template": "[INSECT/AGENT] released by government to control population",
        "crisis_type": "pandemic",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 2,
        "source": "boomlive.in",
        "explanation": "Recurring conspiracy theory with no evidence"
    },
    {
        "claim": "Hospitals in Delhi are injecting patients with wrong medicines intentionally",
        "template": "Hospitals in [CITY] injecting patients with [SUBSTANCE] intentionally",
        "crisis_type": "pandemic",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 3,
        "source": "altnews.in",
        "explanation": "No evidence. Recurring medical conspiracy claim"
    },

    # ── ELECTION ────────────────────────────────────────────
    {
        "claim": "EVM machines have been hacked in all booths of Delhi",
        "template": "EVM machines hacked in [LOCATION] booths",
        "crisis_type": "election",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 5,
        "source": "altnews.in",
        "explanation": "EVMs are not connected to internet. Hacking claim recurs every election"
    },
    {
        "claim": "Votes being bought for Rs 5000 per person in Bihar elections",
        "template": "Votes being bought for [AMOUNT] in [LOCATION] elections",
        "crisis_type": "election",
        "claim_type": "EPHEMERAL",
        "verdict": "UNVERIFIABLE",
        "score": 40,
        "source": "thehindu.com",
        "explanation": "Requires EC investigation. Cannot be confirmed from social media"
    },
    {
        "claim": "Election Commission has postponed elections in all states",
        "template": "Election Commission postponed elections in [LOCATION]",
        "crisis_type": "election",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 7,
        "source": "boomlive.in",
        "explanation": "EC announcements come via official press releases only"
    },
    {
        "claim": "Army has been deployed to rig elections in favour of ruling party",
        "template": "Army deployed to rig elections in favour of [PARTY]",
        "crisis_type": "election",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 4,
        "source": "altnews.in",
        "explanation": "Army deployment is for security only, under EC supervision"
    },

    # ── COMMUNAL / SOCIAL ──────────────────────────────────
    {
        "claim": "Muslim men luring Hindu girls for love jihad in Bangalore",
        "template": "[COMMUNITY] men luring [COMMUNITY] girls in [CITY]",
        "crisis_type": "communal",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 3,
        "source": "altnews.in",
        "explanation": "Love jihad is not recognized as a crime by Supreme Court of India"
    },
    {
        "claim": "Outsiders from Bangladesh are occupying land in Assam",
        "template": "Outsiders from [COUNTRY] occupying land in [STATE]",
        "crisis_type": "communal",
        "claim_type": "SEMI_PERMANENT",
        "verdict": "UNVERIFIABLE",
        "score": 38,
        "source": "thewire.in",
        "explanation": "Complex demographic issue — requires Census data, not forwards"
    },
    {
        "claim": "Churches are converting tribal people forcefully in Jharkhand",
        "template": "[INSTITUTION] converting [COMMUNITY] forcefully in [STATE]",
        "crisis_type": "communal",
        "claim_type": "PERMANENT",
        "verdict": "UNVERIFIABLE",
        "score": 35,
        "source": "thewire.in",
        "explanation": "Requires verified investigation, not social media claims"
    },

    # ── GOVERNMENT / POLICY ────────────────────────────────
    {
        "claim": "Government will freeze all bank accounts above Rs 10 lakh tomorrow",
        "template": "Government will freeze bank accounts above [AMOUNT] [TIME]",
        "crisis_type": "policy",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 3,
        "source": "boomlive.in",
        "explanation": "Recurring financial panic claim. RBI has never done this"
    },
    {
        "claim": "New law allows police to arrest anyone without warrant for 30 days",
        "template": "New law allows police to arrest anyone without warrant for [TIME]",
        "crisis_type": "policy",
        "claim_type": "SEMI_PERMANENT",
        "verdict": "FALSE",
        "score": 10,
        "source": "altnews.in",
        "explanation": "No such law passed. Misrepresentation of UAPA provisions"
    },
    {
        "claim": "Rs 2000 notes are being banned from midnight tonight",
        "template": "Rs [DENOMINATION] notes banned from [TIME]",
        "crisis_type": "policy",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 5,
        "source": "boomlive.in",
        "explanation": "Currency decisions come via official RBI/Finance Ministry announcements"
    },
    {
        "claim": "Aadhaar card will be cancelled if not linked with PAN by tomorrow",
        "template": "[DOCUMENT] will be cancelled if not linked with [DOCUMENT] by [DATE]",
        "crisis_type": "policy",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 8,
        "source": "altnews.in",
        "explanation": "Deadline extensions always announced officially. Check income.tax.gov.in"
    },

    # ── DISASTER / EARTHQUAKE ──────────────────────────────
    {
        "claim": "Scientists predict magnitude 9 earthquake in Delhi within 72 hours",
        "template": "Scientists predict magnitude [NUMBER] earthquake in [CITY] within [TIME]",
        "crisis_type": "earthquake",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 2,
        "source": "boomlive.in",
        "explanation": "Earthquakes cannot be predicted. No scientific body makes such claims"
    },
    {
        "claim": "Nuclear plant in Kudankulam has leaked radiation across Tamil Nadu",
        "template": "Nuclear plant in [LOCATION] leaked radiation across [AREA]",
        "crisis_type": "disaster",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 4,
        "source": "altnews.in",
        "explanation": "AERB monitors all nuclear facilities continuously. No leak reported"
    },

    # ── DEATHS / HISTORICAL ────────────────────────────────
    {
        "claim": "APJ Abdul Kalam is still alive and living in hiding",
        "template": "[DECEASED_PERSON] is still alive and living in [LOCATION]",
        "crisis_type": "historical",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 1,
        "source": "boomlive.in",
        "explanation": "APJ Abdul Kalam passed away on 27 July 2015 in Shillong. Confirmed."
    },
    {
        "claim": "Prime Minister has been arrested by CBI last night",
        "template": "[OFFICIAL] arrested by [AGENCY] last night",
        "crisis_type": "political",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 3,
        "source": "altnews.in",
        "explanation": "Arrest of sitting PM would be front-page news on every outlet"
    },
    {
        "claim": "Sachin Tendulkar has died in a car accident",
        "template": "[CELEBRITY] died in [TYPE] accident",
        "crisis_type": "celebrity",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 2,
        "source": "boomlive.in",
        "explanation": "Celebrity death hoaxes are recurring. Verify via official social media"
    },

    # ── CHILD SAFETY ────────────────────────────────────────
    {
        "claim": "Gang of kidnappers targeting school children in Pune wearing blue shirts",
        "template": "Gang of kidnappers targeting children in [CITY] wearing [DESCRIPTION]",
        "crisis_type": "safety",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 3,
        "source": "altnews.in",
        "explanation": "This exact claim with different cities circulates every few months"
    },
    {
        "claim": "Child traffickers operating in [CITY] hospital, avoid maternity ward",
        "template": "Child traffickers operating in [LOCATION] hospital",
        "crisis_type": "safety",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 4,
        "source": "boomlive.in",
        "explanation": "Recurring hospital trafficking panic. No police FIR filed in any case"
    },

    # ── FOOD / MEDICINE ─────────────────────────────────────
    {
        "claim": "Maggi noodles contain pig fat and are banned in all states",
        "template": "[FOOD_PRODUCT] contains [INGREDIENT] and banned in [LOCATION]",
        "crisis_type": "food",
        "claim_type": "PERMANENT",
        "verdict": "FALSE",
        "score": 5,
        "source": "altnews.in",
        "explanation": "Maggi ban was lifted by Supreme Court in 2015. Pig fat claim is false"
    },
    {
        "claim": "Onion prices will rise to Rs 500 per kg tomorrow due to government export",
        "template": "[COMMODITY] prices will rise to [PRICE] [TIME] due to [REASON]",
        "crisis_type": "economic",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 9,
        "source": "boomlive.in",
        "explanation": "Price prediction claims are unverifiable and cause unnecessary panic"
    },

    # ── MILITARY / SECURITY ─────────────────────────────────
    {
        "claim": "India and Pakistan have officially declared war as of this morning",
        "template": "[COUNTRY1] and [COUNTRY2] officially declared war",
        "crisis_type": "military",
        "claim_type": "EPHEMERAL",
        "verdict": "FALSE",
        "score": 2,
        "source": "altnews.in",
        "explanation": "War declarations are official government acts covered by all media"
    },
    {
        "claim": "Chinese troops have crossed LAC and occupied Ladakh villages",
        "template": "[COUNTRY] troops crossed [BORDER] and occupied [LOCATION]",
        "crisis_type": "military",
        "claim_type": "EPHEMERAL",
        "verdict": "UNVERIFIABLE",
        "score": 38,
        "source": "thehindu.com",
        "explanation": "Requires Ministry of Defence confirmation. Verify via official sources"
    },
]

print(f"  ✓ Loaded {len(KNOWN_FAKE_CLAIMS)} known fake claims from archive")

# ─────────────────────────────────────────────────────────────
# STEP 4 — Scrape Alt News + BOOM Live for additional claims
# ─────────────────────────────────────────────────────────────

print("\n[5/6] Scraping fact-check sites for additional claims...")
print("─" * 50)

SCRAPED_CLAIMS = []

SCRAPE_SOURCES = [
    {
        "name": "Alt News",
        "rss":  "https://www.altnews.in/feed/",
        "source_key": "altnews.in",
        "weight": 0.95,
    },
    {
        "name": "BOOM Live",
        "rss":  "https://www.boomlive.in/feed",
        "source_key": "boomlive.in",
        "weight": 0.95,
    },
    {
        "name": "Vishvas News",
        "rss":  "https://www.vishvasnews.com/feed/",
        "source_key": "vishvasnews.com",
        "weight": 0.90,
    },
    {
        "name": "The Hindu",
        "rss":  "https://www.thehindu.com/news/feeder/default.rss",
        "source_key": "thehindu.com",
        "weight": 0.90,
    },
    {
        "name": "Indian Express",
        "rss":  "https://indianexpress.com/feed/",
        "source_key": "indianexpress.com",
        "weight": 0.90,
    },
    {
        "name": "NDTV",
        "rss":  "https://feeds.feedburner.com/ndtvnews-top-stories",
        "source_key": "ndtv.com",
        "weight": 0.88,
    },
    {
        "name": "PIB",
        "rss":  "https://pib.gov.in/RssMain.aspx?ModID=6&Lang=1",
        "source_key": "pib.gov.in",
        "weight": 0.95,
    },
    {
        "name": "IMD",
        "rss":  "https://mausam.imd.gov.in/imd_latest/contents/rss-feed.php",
        "source_key": "imd.gov.in",
        "weight": 0.95,
    },
]

RSS_DOCUMENTS = []  # for FAISS knowledge base

headers = {
    "User-Agent": "Mozilla/5.0 (compatible; TruthSetu/1.0; research bot)"
}

for source in SCRAPE_SOURCES:
    try:
        print(f"  Fetching {source['name']}...", end=" ")
        feed = feedparser.parse(source["rss"])

        count = 0
        for entry in feed.entries[:30]:
            title   = entry.get("title", "").strip()
            summary = entry.get("summary", "").strip()
            link    = entry.get("link", "")
            date    = entry.get("published", "")

            if not title:
                continue

            # Clean HTML from summary
            if summary:
                soup = BeautifulSoup(summary, "html.parser")
                summary = soup.get_text(separator=" ").strip()[:500]

            full_text = f"{title}. {summary}".strip()

            # Skip rumour-reporting chunks
            rumour_phrases = [
                "viral message claims", "whatsapp forward",
                "rumours suggest", "unverified reports",
                "social media claims", "it is being claimed",
                "fake news", "fact check:"
            ]

            is_rumour_report = any(
                p in full_text.lower() for p in rumour_phrases
            )

            RSS_DOCUMENTS.append({
                "text":        full_text,
                "source":      source["source_key"],
                "url":         link,
                "weight":      source["weight"],
                "tier":        "fact_check" if "altnews" in source["source_key"]
                               or "boom" in source["source_key"]
                               or "vishvas" in source["source_key"]
                               else "news",
                "date":        date,
                "is_rumour_report": is_rumour_report,
            })
            count += 1

        print(f"✓ {count} entries")

    except Exception as e:
        print(f"✗ Failed ({e})")

print(f"\n  ✓ Total RSS documents collected: {len(RSS_DOCUMENTS)}")

# ─────────────────────────────────────────────────────────────
# STEP 5 — Embed and seed everything
# ─────────────────────────────────────────────────────────────

print("\n[6/6] Building embeddings and seeding database...")
print("─" * 50)

print("  Loading sentence-transformers model (first run downloads ~90MB)...")
embedder = SentenceTransformer(EMBEDDING_MODEL)
print("  ✓ Model loaded")

# ── 5a. Seed MongoDB templates ─────────────────────────────
print("\n  Seeding template store...")

templates_collection = db["templates"]
training_collection  = db["training_data"]

seeded = 0
for item in tqdm(KNOWN_FAKE_CLAIMS, desc="  Templates"):

    # Generate embedding for the claim
    embedding = embedder.encode(item["claim"]).tolist()

    template_doc = {
        "template_text":    item["template"],
        "example_claim":    item["claim"],
        "crisis_type":      item["crisis_type"],
        "claim_type":       item["claim_type"],
        "verdict":          item["verdict"],
        "credibility_score": item["score"],
        "source":           item["source"],
        "explanation":      item["explanation"],
        "embedding":        embedding,
        "first_seen":       datetime.utcnow(),
        "last_seen":        datetime.utcnow(),
        "occurrence_count": 1,
        "seeded":           True,
    }

    # Upsert — don't duplicate if script is run again
    templates_collection.update_one(
        {"template_text": item["template"]},
        {"$set": template_doc},
        upsert=True
    )

    # Also add to classifier training data
    training_collection.insert_one({
        "text":   item["claim"],
        "label":  1 if item["verdict"] == "FALSE" else 0,
        "source": "seeded_archive",
        "date":   datetime.utcnow(),
    })

    seeded += 1

print(f"  ✓ {seeded} templates seeded into MongoDB")

# ── 5b. Build FAISS index from RSS documents ───────────────
print("\n  Building FAISS knowledge base...")

# Filter out rumour-reporting chunks for FAISS
clean_docs = [d for d in RSS_DOCUMENTS if not d.get("is_rumour_report")]
print(f"  {len(RSS_DOCUMENTS)} total docs → {len(clean_docs)} after filtering")

if clean_docs:
    texts = [d["text"] for d in clean_docs]

    print(f"  Embedding {len(texts)} documents...")
    embeddings = embedder.encode(
        texts,
        show_progress_bar=True,
        batch_size=32
    )
    embeddings = np.array(embeddings, dtype=np.float32)

    # Normalise for cosine similarity
    faiss.normalize_L2(embeddings)

    # Build flat IP index
    dim   = embeddings.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(embeddings)

    # Save index
    index_path = FAISS_DIR / "index.faiss"
    docs_path  = FAISS_DIR / "documents.json"

    faiss.write_index(index, str(index_path))
    with open(docs_path, "w") as f:
        json.dump(clean_docs, f, indent=2)

    print(f"  ✓ FAISS index built: {len(clean_docs)} documents")
    print(f"  ✓ Saved to {index_path}")

else:
    print("  ⚠ No RSS documents fetched — FAISS index empty")
    print("    This is okay, it will build on first VERIFY run")

# ── 5c. Seed source scores with defaults ──────────────────
print("\n  Seeding source quality scores...")

default_source_scores = [
    {"source": "pib.gov.in",          "weight": 0.95, "tier": "government"},
    {"source": "imd.gov.in",          "weight": 0.95, "tier": "government"},
    {"source": "ndma.gov.in",         "weight": 0.95, "tier": "government"},
    {"source": "mohfw.gov.in",        "weight": 0.90, "tier": "government"},
    {"source": "who.int",             "weight": 0.90, "tier": "government"},
    {"source": "altnews.in",          "weight": 0.95, "tier": "fact_check"},
    {"source": "boomlive.in",         "weight": 0.95, "tier": "fact_check"},
    {"source": "vishvasnews.com",     "weight": 0.90, "tier": "fact_check"},
    {"source": "thehindu.com",        "weight": 0.90, "tier": "tier1_news"},
    {"source": "indianexpress.com",   "weight": 0.90, "tier": "tier1_news"},
    {"source": "ndtv.com",            "weight": 0.88, "tier": "tier1_news"},
    {"source": "ptinews.com",         "weight": 0.90, "tier": "tier1_news"},
    {"source": "timesofindia.com",    "weight": 0.80, "tier": "tier2_news"},
    {"source": "hindustantimes.com",  "weight": 0.80, "tier": "tier2_news"},
    {"source": "thewire.in",          "weight": 0.82, "tier": "tier2_news"},
    {"source": "theprint.in",         "weight": 0.80, "tier": "tier2_news"},
    {"source": "scroll.in",           "weight": 0.78, "tier": "tier2_news"},
    {"source": "deccanherald.com",    "weight": 0.75, "tier": "regional"},
    {"source": "tribuneindia.com",    "weight": 0.75, "tier": "regional"},
    {"source": "wikipedia.org",       "weight": 0.85, "tier": "encyclopedia"},
]

for score in default_source_scores:
    db["source_scores"].update_one(
        {"source": score["source"]},
        {"$setOnInsert": {
            **score,
            "total_appearances": 0,
            "helpful_count":     0,
            "created_at":        datetime.utcnow(),
        }},
        upsert=True
    )

print(f"  ✓ {len(default_source_scores)} source scores seeded")

# ─────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────

print("\n" + "═" * 50)
print("  TruthSetu Setup Complete!")
print("═" * 50)

template_count = db["templates"].count_documents({})
training_count = db["training_data"].count_documents({})
source_count   = db["source_scores"].count_documents({})

print(f"""
  MongoDB '{DB_NAME}' database:
  ├─ templates:      {template_count} fake claim templates
  ├─ training_data:  {training_count} classifier examples
  ├─ source_scores:  {source_count} sources tracked
  └─ All collections + indexes created

  FAISS knowledge base:
  └─ {len(clean_docs) if clean_docs else 0} documents indexed
     at {FAISS_DIR}/index.faiss

  Config:
  └─ .env file created (fill in your API keys)

  Next steps:
  ─────────────────────────────────────────
  1. Fill in .env with your API keys:
     - GROQ_API_KEY    → console.groq.com (free)
     - GREEN_API keys  → green-api.com (free 3 months)
     - TELEGRAM_BOT_TOKEN → @BotFather on Telegram

  2. Install backend dependencies:
     pip install -r requirements.txt

  3. Start the server:
     uvicorn backend.main:app --reload

  4. Test VERIFY:
     curl -X POST http://localhost:8000/api/v1/verify \\
       -H "Content-Type: application/json" \\
       -d '{{"claim": "Cyclone will hit Chennai in 2 hours"}}'
""")

client.close()
